name: Briefcase Build

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v[0-9].*'

jobs:
  briefcase:
    name: Bundle on ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-12, windows-2022]
        python-version: ["3.8"]
      fail-fast: false
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Python libs
        run: |
          python -m pip install --upgrade pip
          python -m pip install briefcase==0.3.11
          python -m pip freeze

      - name: Create and Build Bundle
        run: |
          briefcase create
          briefcase build

      - name: Package Mac
        if: runner.os == 'macOS'
        run: briefcase package --no-sign

      - name: Package Windows
        if: runner.os == 'Windows'
        run: briefcase package

      - name: Package Linux
        if: runner.os == 'Linux'
        run: briefcase package

      - name: Upload Artifact for Linux
        uses: actions/upload-artifact@v3
        if: runner.os == 'Linux'
        with:
          name: memory-master-mind-${{ github.ref_name }}-${{ matrix.os }}.AppImage
          path: '**/*.AppImage'

      - name: Upload Artifact for MacOS
        uses: actions/upload-artifact@v3
        if: runner.os == 'MacOS'
        with:
          name: memory-master-mind-${{ github.ref_name }}-${{ matrix.os }}.dmg
          path: '**/*.dmg'

      - name: Upload Artifact for Windows
        uses: actions/upload-artifact@v3
        if: runner.os == 'Windows'
        with:
          name: memory-master-mind-${{ github.ref_name }}-${{ matrix.os }}.msi
          path: '**/*.msi'
