name: PyInstaller Build

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v[0-9].*'

jobs:
  briefcase:
    name: Bundle on ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
        python-version: ["3.8"]
      fail-fast: false
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Python libs
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Windows Build
        if: runner.os == 'Windows'
        run: |
          pyinstaller run.py --name "Memory Master Mind" --onefile -w --clean --noupx -i "memory_master_mind\assets\icons\appicons\mmm.ico" --add-data "memory_master_mind\assets;memory_master_mind\assets"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: memory-master-mind-${{ github.ref_name }}-${{ matrix.os }}.exe
          path: 'dist/Memory Master Mind.exe'
